### ISSUE TITLE
Concurrent creation of database for parallel inserts doesn't work when database doesn't exist

### ISSUE THREAD

**Issue by rumyantseva** [FerretDB/FerretDB#1488]
### Versions

Nov 17, `main`

### What did you do?

Run dance tests and got an internal error

```
document_validation_test.go:112: 
        	Error Trace:	/home/user/dance/tests/diff/document_validation_test.go:112
        	Error:      	Received unexpected error:
        	            	(InternalError) [pool.go:213 pgdb.(*Pool).InTransaction] [error.go:200 common.CheckError] [insert.go:44 pgdb.InsertDocument] database/schema or collection/table already exist
        	Test:       	TestDocumentValidation/Update/DollarSign
        --- FAIL: TestDocumentValidation/Update/DollarSign (0.03s)
```

### What did you expect to see?

No errors

### What did you see instead?

DB already exists error.

### Reasoning

This is what `CreateDatabaseIfNotExists` promises (` If the schema already exists, no error is returned`):

```go
// CreateDatabaseIfNotExists creates a new FerretDB database (PostgreSQL schema).
// If the schema already exists, no error is returned, and transaction is not aborted.
func CreateDatabaseIfNotExists(ctx context.Context, tx pgx.Tx, db string) error {
```

This is what this function could return in fact:

```go
	case pgerrcode.DuplicateSchema:
		return ErrAlreadyExist
	case pgerrcode.UniqueViolation, pgerrcode.DuplicateObject:
		// https://www.postgresql.org/message-id/CA+TgmoZAdYVtwBfp1FL2sMZbiHCWT4UPrzRLNnX1Nb30Ku3-gg@mail.gmail.com
		// The same thing for schemas. Reproducible by integration tests.
		return ErrAlreadyExist
```

In addition to that, the statement that  `transaction is not aborted` is false. If `PgError` is caught, the transaction *will be* aborted (`current transaction is aborted, commands ignored until end of transaction block`).

### TODO

- [x] If possible, add a stress test to reproduce the problem on FerrretDB itself (e.g. parallel insert into the same database that doesn't exist)
- [x]  Fix the problem (e.g. fix godoc, check for `ErrAlreadyExists` in callers, use multiple transactions when needed - like [here](https://github.com/FerretDB/FerretDB/blob/af2554ad143a40afb110b4277995507af7873f73/internal/handlers/pg/msg_create.go#L75))
- [ ] Check dance for the current issue being mentioned and fix relevant TODOs

**Comment by rumyantseva** [comment]
Stress tests: Something similar to `TestCreateStress`, but
- Use a new database (that doesn't exist anymore) - the same for all the new collections
- In the first stress test use a few different collections, in the second stress test use the same collection 
- Call insert (so we attempt to insert into database that doesn't exist)
