### ISSUE TITLE
Support `find`'s / `aggregate`'s / `getMore`'s `maxTimeMS` parameter

### ISSUE THREAD

**Issue by w84thesun** [FerretDB/FerretDB#1808]
### What should be done?

https://www.mongodb.com/docs/manual/reference/command/getMore/

As we don't support backend-side cursors for now just return from `getMore` when timeout is exceeded potentially removing cursor from `connInfo`.

See also:
https://www.mongodb.com/docs/manual/reference/method/cursor.maxTimeMS/
https://github.com/mongodb/specifications/blob/master/source/client-side-operations-timeout/client-side-operations-timeout.rst#cursors
```[tasklist]
### Tasks
- [ ] https://github.com/FerretDB/FerretDB/issues/2983
- [ ] https://github.com/FerretDB/FerretDB/issues/2963
- [ ] https://github.com/FerretDB/FerretDB/issues/2984
```
