### ISSUE TITLE
Achieve compatibility with Strapi

### ISSUE THREAD

**Issue by b1ron** [FerretDB/FerretDB#1822]
### What should be done?

I have only tested this on v3. We cannot run their [tests](https://github.com/strapi/strapi/blob/v3.4.3/CONTRIBUTING.md#running-the-tests) because they require a user with the SCRAM-SHA-256 mechanism in the `admin` database.

```[tasklist]
### Tasks
- [ ] https://github.com/FerretDB/FerretDB/issues/825
- [ ] https://github.com/FerretDB/FerretDB/issues/826
- [ ] https://github.com/FerretDB/FerretDB/issues/1491
- [ ] https://github.com/FerretDB/FerretDB/issues/7 
- [ ] https://github.com/FerretDB/FerretDB/issues/1428
- [ ] https://github.com/FerretDB/FerretDB/issues/1439
- [ ] https://github.com/FerretDB/FerretDB/issues/1467
```

They seemed to have removed their [API integrations tests for MongoDB](https://github.com/strapi/strapi/blob/main/CONTRIBUTING.md#running-the-api-integration-tests) in v4.

In this [blog post](https://strapi.io/blog/mongo-db-support-in-strapi-past-present-and-future) they mention that MongoDB usage represents less than 0.4% of all the Strapi projects and the connector will not be supported natively in v4 but should be in later versions.

**Comment by AlekSi** [comment]
They dropped MongoDB support
