### ISSUE TITLE
Achieve compatibility with NewsBlur

### ISSUE THREAD

**Issue by b1ron** [FerretDB/FerretDB#2014]
### What should be done?

```[tasklist]
### Tasks
- [ ] https://github.com/FerretDB/FerretDB/issues/1491
- [ ] https://github.com/FerretDB/FerretDB/issues/1493
- [ ] https://github.com/FerretDB/FerretDB/issues/1423
- [ ] https://github.com/FerretDB/FerretDB/issues/2013
- [ ] https://github.com/FerretDB/FerretDB/issues/76
- [ ] https://github.com/FerretDB/FerretDB/issues/2012
- [ ] https://github.com/FerretDB/FerretDB/issues/7
- [ ] https://github.com/FerretDB/FerretDB/issues/78
```
