### ISSUE TITLE
Achieve compatibility with Apache Allura

### ISSUE THREAD

**Issue by b1ron** [FerretDB/FerretDB#2029]
### What should be done?

In order to [initialize the database with test data](https://forge-allura.apache.org/docs/getting_started/installation.html#containers) we need to support the SCRAM-SHA-1 authentication mechanism as PyMongo connects using this mechanism by default it seems. However, PLAIN is supported as seen [here](https://pymongo.readthedocs.io/en/stable/api/pymongo/database.html#pymongo.auth.MECHANISMS).

```[tasklist]
### Tasks
- [ ] https://github.com/FerretDB/FerretDB/issues/2012
- [ ] https://github.com/FerretDB/FerretDB/issues/78
- [ ] https://github.com/FerretDB/FerretDB/issues/825
- [ ] https://github.com/FerretDB/FerretDB/issues/1439
- [ ] https://github.com/FerretDB/FerretDB/issues/1491
- [ ] https://github.com/FerretDB/FerretDB/issues/2013
- [ ] https://github.com/FerretDB/FerretDB/issues/2026
- [ ] https://github.com/FerretDB/FerretDB/issues/2027
- [ ] https://github.com/FerretDB/FerretDB/issues/2028
```
