### ISSUE TITLE
Achieve compatibility with Scale8

### ISSUE THREAD

**Issue by b1ron** [FerretDB/FerretDB#2033]
### What should be done?

We are basically compatible with Scale8 according to their integration test results. The 2 failures below occur when run using diff-proxy mode. Those two `created_at` values appear in the tests and are not generated so they seem to be unrelated.

```
    -         "created_at": 1608175440000,
    +         "created_at": 1608171840000,
...
Test Suites: 2 failed, 37 passed, 39 total
Tests:       2 failed, 90 passed, 92 total
Snapshots:   2 failed, 31 passed, 33 total
Time:        45.957 s
Ran all test suites.
```

From grepping through [this](https://github.com/scale8/scale8-tag-manager-and-analytics/blob/master/api/src/backends/databases/MongoDb.ts) file I found the below:

```[tasklist]
### Tasks
- [ ] https://github.com/FerretDB/FerretDB/issues/2013
- [ ] https://github.com/FerretDB/FerretDB/issues/1428
- [ ] https://github.com/FerretDB/FerretDB/issues/1423
- [ ] https://github.com/FerretDB/FerretDB/issues/1439
- [ ] https://github.com/FerretDB/FerretDB/issues/1413
- [ ] https://github.com/FerretDB/FerretDB/issues/1432
- [ ] https://github.com/FerretDB/FerretDB/issues/1467
- [ ] https://github.com/FerretDB/FerretDB/issues/1453
- [ ] https://github.com/FerretDB/FerretDB/issues/1466
```

**Comment by AlekSi** [comment]
@b1ron Please run https://github.com/awslabs/amazon-documentdb-tools/tree/master/compat-tool on it

**Comment by b1ron** [comment]
Done @AlekSi.
