### ISSUE TITLE
Support lazy BSON decoding

### ISSUE THREAD

**Issue by AlekSi** [FerretDB/FerretDB#3759]
### What should be done?

BSON documents and arrays should support lazy decoding and encoding. For example, there is no need to decode the whole huge command document only to learn that the first key (command) is incorrect.

That is also an opportunity for us to make fewer memory allocations and make them more precise. Ideally, we should use a pool of byte slices and reuse them as much as possible.

```[tasklist]
### Tasks
- [x] Add a way to check document/array without decoding
- [x] Improve cross-tests
- [x] Improve fuzzing
- [x] Improve LogValue methods and logging in general
- [x] Fix logging of deeply nested documents/arrays
- [ ] Add benchmarks
- [ ] Check decoding logic for offsets
- [ ] Convert encoding to accept byte slices instead of returning them
- [ ] Use pools of slices? For converting `[]bson2.RawDocument` too?
- [ ] Make fuzzing inputs smaller (see [there](https://afl-1.readthedocs.io/en/latest/tips.html#performance-tips))
```

### Where?

* https://github.com/FerretDB/FerretDB/tree/main/internal/bson
* https://github.com/FerretDB/FerretDB/tree/main/internal/wire

### Definition of Done

TBD

- handler updated;
- all backends updated;
- unit tests added/updated;
- integration/compatibility tests added/updated;
- spot refactorings done;
- user documentation updated or an issue to create documentation created;
- something else?
